/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

import model.User;
import service.ReportService;
import util.SmartKitchenTheme;

/**
 *
 * @author ntgr
 */
public class AdminDashboardView extends javax.swing.JFrame {

    private User currentUser;
    private JLabel lblWelcome;
    private JLabel lblRole;
    private JLabel lblAvatar;
    private JLabel lblTotalRevenue;
    private JLabel lblTotalOrders;
    private JLabel lblTotalSpend;
    private JLabel lblTotalPurchases;

    /**
     * Creates new form AdminDashboardView
     */
    public AdminDashboardView() {
        initComponents();
    }

    public AdminDashboardView(User user) {
        this.currentUser = user;
        initComponents();
        applyUserContext();
        loadSummaries();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Kitchen - Admin Dashboard");

        JLabel lblLogo = new JLabel();
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/images/logo.png"));
        java.awt.Image scaledLogo = logoIcon.getImage().getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
        lblLogo.setIcon(new ImageIcon(scaledLogo));

        lblWelcome = new JLabel("Welcome, Admin");
        lblWelcome.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 16));

        lblRole = new JLabel("");

        lblAvatar = new JLabel("A", javax.swing.SwingConstants.CENTER);
        lblAvatar.setPreferredSize(new java.awt.Dimension(32, 32));
        lblAvatar.setOpaque(true);
        lblAvatar.setBackground(SmartKitchenTheme.ACCENT_GREEN);
        lblAvatar.setForeground(java.awt.Color.BLACK);

        JButton btnLogout = new JButton("Logout");
        btnLogout.addActionListener(e -> {
            new LoginView().setVisible(true);
            this.dispose();
        });

        JPanel headerPanel = new JPanel();
        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblLogo)
                .addGap(10, 10, 10)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnLogout)
                .addGap(10, 10, 10))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogo)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addGap(2, 2, 2)
                        .addComponent(lblRole))
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(10, 10, 10))
        );

        JPanel navPanel = new JPanel();
        JButton btnNavDashboard = new JButton("Dashboard") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavUsers = new JButton("Users") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavMenus = new JButton("Menus") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavReports = new JButton("Reports") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavSettings = new JButton("Settings") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnNavDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavMenus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavSettings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNavDashboard)
                    .addComponent(btnNavUsers)
                    .addComponent(btnNavMenus)
                    .addComponent(btnNavReports)
                    .addComponent(btnNavSettings))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        lblTotalRevenue = new JLabel("Total Revenue: -");
        lblTotalOrders = new JLabel("Total Orders: -");
        lblTotalSpend = new JLabel("Total Spend: -");
        lblTotalPurchases = new JLabel("Total Purchases: -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(lblTotalOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalSpend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalPurchases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblTotalRevenue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalOrders)
                .addGap(16, 16, 16)
                .addComponent(lblTotalSpend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPurchases)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        SmartKitchenTheme.applyRoot(this);
        SmartKitchenTheme.styleCard(headerPanel);
        SmartKitchenTheme.styleCard(navPanel);
        SmartKitchenTheme.stylePrimaryLabel(lblWelcome);
        SmartKitchenTheme.styleSecondaryLabel(lblRole);
        SmartKitchenTheme.styleSecondaryLabel(lblTotalRevenue);
        SmartKitchenTheme.styleSecondaryLabel(lblTotalOrders);
        SmartKitchenTheme.styleSecondaryLabel(lblTotalSpend);
        SmartKitchenTheme.styleSecondaryLabel(lblTotalPurchases);

        JButton[] navButtons = { btnNavDashboard, btnNavUsers, btnNavMenus, btnNavReports, btnNavSettings };
        for (JButton b : navButtons) {
            SmartKitchenTheme.styleGradientButton(b);
        }

        btnNavDashboard.addActionListener(e -> loadSummaries());

        btnNavUsers.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "TODO: Users screen", "Not implemented",
                    JOptionPane.INFORMATION_MESSAGE);
        });

        btnNavMenus.addActionListener(e -> {
            if (currentUser != null) {
                new MenuView(currentUser).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No user context.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        });

        btnNavReports.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "TODO: Reports screen", "Not implemented",
                    JOptionPane.INFORMATION_MESSAGE);
        });

        btnNavSettings.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "TODO: Settings screen", "Not implemented",
                    JOptionPane.INFORMATION_MESSAGE);
        });
    }// </editor-fold>//GEN-END:initComponents

    private void applyUserContext() {
        if (currentUser != null) {
            String name = currentUser.getUsername() != null && !currentUser.getUsername().isEmpty()
                    ? currentUser.getUsername()
                    : (currentUser.getEmail() != null ? currentUser.getEmail() : "Admin");
            lblWelcome.setText("Welcome, " + name);
            lblRole.setText("Role: " + currentUser.getRole());
        }
    }

    private void loadSummaries() {
        if (currentUser == null || currentUser.getToken() == null) {
            return;
        }
        try {
            ReportService service = new ReportService();
            ReportService.SalesSummary sales = service.getSalesSummary(currentUser.getToken());
            ReportService.PurchaseSummary purchase = service.getPurchaseSummary(currentUser.getToken());

            lblTotalRevenue.setText("Total Revenue: " + String.format("%.2f", sales.totalRevenue));
            lblTotalOrders.setText("Total Orders: " + sales.totalOrders);
            lblTotalSpend.setText("Total Spend: " + String.format("%.2f", purchase.totalSpend));
            lblTotalPurchases.setText("Total Purchases: " + purchase.totalPurchases);
        } catch (Exception ex) {
            lblTotalRevenue.setText("Total Revenue: -");
            lblTotalOrders.setText("Total Orders: -");
            lblTotalSpend.setText("Total Spend: -");
            lblTotalPurchases.setText("Total Purchases: -");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
