/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

import model.User;
import util.SmartKitchenTheme;

/**
 *
 * @author ntgr
 */
public class CashierDashboardView extends javax.swing.JFrame {

    private User currentUser;
    private JLabel lblWelcome;
    private JLabel lblRole;
    private JLabel lblAvatar;

    /**
     * Creates new form CashierDashboardView
     */
    public CashierDashboardView() {
        initComponents();
    }

    public CashierDashboardView(User user) {
        this.currentUser = user;
        initComponents();
        applyUserContext();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Kitchen - Cashier Dashboard");

        JLabel lblLogo = new JLabel();
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/images/logo.png"));
        java.awt.Image scaledLogo = logoIcon.getImage().getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
        lblLogo.setIcon(new ImageIcon(scaledLogo));

        lblWelcome = new JLabel("Welcome, Cashier");
        lblWelcome.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 16));

        lblRole = new JLabel("");

        lblAvatar = new JLabel("C", javax.swing.SwingConstants.CENTER);
        lblAvatar.setPreferredSize(new java.awt.Dimension(32, 32));
        lblAvatar.setOpaque(true);
        lblAvatar.setBackground(SmartKitchenTheme.ACCENT_GREEN);
        lblAvatar.setForeground(java.awt.Color.BLACK);

        JButton btnLogout = new JButton("Logout");
        btnLogout.addActionListener(e -> {
            new LoginView().setVisible(true);
            this.dispose();
        });

        JPanel headerPanel = new JPanel();
        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblLogo)
                .addGap(10, 10, 10)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnLogout)
                .addGap(10, 10, 10))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogo)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addGap(2, 2, 2)
                        .addComponent(lblRole))
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(10, 10, 10))
        );

        JPanel navPanel = new JPanel();
        JButton btnNavDashboard = new JButton("Dashboard") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavBills = new JButton("Bills") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavPayments = new JButton("Payments") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavReports = new JButton("Reports") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavSettings = new JButton("Settings") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnNavDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavBills)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavPayments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavSettings)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNavDashboard)
                    .addComponent(btnNavBills)
                    .addComponent(btnNavPayments)
                    .addComponent(btnNavReports)
                    .addComponent(btnNavSettings))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        SmartKitchenTheme.applyRoot(this);
        SmartKitchenTheme.styleCard(headerPanel);
        SmartKitchenTheme.styleCard(navPanel);
        SmartKitchenTheme.stylePrimaryLabel(lblWelcome);
        SmartKitchenTheme.styleSecondaryLabel(lblRole);

        JButton[] navButtons = { btnNavDashboard, btnNavBills, btnNavPayments, btnNavReports, btnNavSettings };
        for (JButton b : navButtons) {
            SmartKitchenTheme.styleGradientButton(b);
        }

        btnNavDashboard.addActionListener(e -> {
            javax.swing.JOptionPane.showMessageDialog(this, "TODO: Cashier dashboard overview", "Not implemented",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });

        btnNavBills.addActionListener(e -> {
            new CashierBillsView().setVisible(true);
        });

        btnNavPayments.addActionListener(e -> {
            new CashierPaymentsView().setVisible(true);
        });

        btnNavReports.addActionListener(e -> {
            javax.swing.JOptionPane.showMessageDialog(this, "TODO: Reports screen", "Not implemented",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });

        btnNavSettings.addActionListener(e -> {
            javax.swing.JOptionPane.showMessageDialog(this, "TODO: Settings screen", "Not implemented",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });
    }// </editor-fold>//GEN-END:initComponents

    private void applyUserContext() {
        if (currentUser != null) {
            String name = currentUser.getUsername() != null && !currentUser.getUsername().isEmpty()
                    ? currentUser.getUsername()
                    : (currentUser.getEmail() != null ? currentUser.getEmail() : "Cashier");
            lblWelcome.setText("Welcome, " + name);
            lblRole.setText("Role: " + currentUser.getRole());
            if (lblAvatar != null && name != null && !name.isEmpty()) {
                lblAvatar.setText(name.substring(0, 1).toUpperCase());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierDashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
