/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import model.User;
import service.UserService;
import util.SmartKitchenTheme;

/**
 *
 * @author ntgr
 */
public class LoginView extends javax.swing.JFrame {

    private JTextField txtUsernameOrEmail;
    private JPasswordField txtPassword;
    private JButton btnLogin;
    private JLabel lblError;

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Kitchen - Login");
        setResizable(false);

        JLabel lblLogo = new JLabel();
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/images/logo.png"));
        java.awt.Image scaled = logoIcon.getImage().getScaledInstance(96, 96, java.awt.Image.SCALE_SMOOTH);
        lblLogo.setIcon(new ImageIcon(scaled));

        JLabel lblTitle = new JLabel("SMART KITCHEN");
        lblTitle.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 20));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        JLabel lblSubtitle = new JLabel("Sign in to continue");
        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        JLabel lblUser = new JLabel("Email or Username");
        txtUsernameOrEmail = new JTextField();

        JLabel lblPass = new JLabel("Password");
        txtPassword = new JPasswordField();

        btnLogin = new JButton("Login");
        btnLogin.addActionListener(evt -> onLogin());

        lblError = new JLabel("");
        lblError.setForeground(new java.awt.Color(255, 80, 80));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsernameOrEmail)
                    .addComponent(lblPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo)
                .addGap(10, 10, 10)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(24, 24, 24)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsernameOrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblError)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setSize(480, 560);
        setLocationRelativeTo(null);

        SmartKitchenTheme.applyRoot(this);
        SmartKitchenTheme.stylePrimaryLabel(lblTitle);
        SmartKitchenTheme.styleSecondaryLabel(lblSubtitle);
        SmartKitchenTheme.styleSecondaryLabel(lblUser);
        SmartKitchenTheme.styleSecondaryLabel(lblPass);
        SmartKitchenTheme.styleSecondaryLabel(lblError);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    private void onLogin() {
        lblError.setText("");

        String identifier = txtUsernameOrEmail.getText().trim();
        String password = new String(txtPassword.getPassword());

        if (identifier.isEmpty() || password.isEmpty()) {
            lblError.setText("Please enter both username/email and password.");
            return;
        }

        btnLogin.setEnabled(false);
        try {
            UserService service = new UserService();
            User user = service.login(identifier, password);

            if (user == null || user.getRole() == null) {
                lblError.setText("Login failed: invalid response.");
                btnLogin.setEnabled(true);
                return;
            }

            openDashboardForRole(user);
        } catch (Exception ex) {
            lblError.setText(ex.getMessage());
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Login Failed", JOptionPane.ERROR_MESSAGE);
        } finally {
            btnLogin.setEnabled(true);
        }
    }

    private void openDashboardForRole(User user) {
        String role = user.getRole();
        javax.swing.JFrame next;

        if ("admin".equalsIgnoreCase(role)) {
            next = new AdminDashboardView(user);
        } else if ("manager".equalsIgnoreCase(role)) {
            next = new ManagerDashboardView(user);
        } else if ("chef".equalsIgnoreCase(role)) {
            next = new ChefDashboardView(user);
        } else if ("waiter".equalsIgnoreCase(role)) {
            next = new WaiterDashboardView(user);
        } else if ("cashier".equalsIgnoreCase(role)) {
            next = new CashierDashboardView(user);
        } else {
            JOptionPane.showMessageDialog(this, "Unknown role: " + role, "Login", JOptionPane.WARNING_MESSAGE);
            return;
        }

        next.setLocationRelativeTo(this);
        next.setVisible(true);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
