/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import model.User;
import service.ReportService;
import util.SmartKitchenTheme;

/**
 *
 * @author ntgr
 */
public class ManagerDashboardView extends javax.swing.JFrame {

    private User currentUser;
    private JLabel lblWelcome;
    private JLabel lblRole;
    private JLabel lblAvatar;
    private JLabel lblSalesDays;
    private JLabel lblWaiterPerf;
    private JLabel lblChefPerf;
    private JTable tableWaiters;
    private JTable tableChefs;
    private JScrollPane scrollWaiters;
    private JScrollPane scrollChefs;

    /**
     * Creates new form ManagerDashboardView
     */
    public ManagerDashboardView() {
        initComponents();
    }

    public ManagerDashboardView(User user) {
        this.currentUser = user;
        initComponents();
        applyUserContext();
        loadManagerMetrics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Kitchen - Manager Dashboard");

        JLabel lblLogo = new JLabel();
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/images/logo.png"));
        java.awt.Image scaledLogo = logoIcon.getImage().getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
        lblLogo.setIcon(new ImageIcon(scaledLogo));

        lblWelcome = new JLabel("Welcome, Manager");
        lblWelcome.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 16));

        lblRole = new JLabel("");

        lblAvatar = new JLabel("M", javax.swing.SwingConstants.CENTER);
        lblAvatar.setPreferredSize(new java.awt.Dimension(32, 32));
        lblAvatar.setOpaque(true);
        lblAvatar.setBackground(SmartKitchenTheme.ACCENT_GREEN);
        lblAvatar.setForeground(java.awt.Color.BLACK);

        JButton btnLogout = new JButton("Logout");
        btnLogout.addActionListener(e -> {
            new LoginView().setVisible(true);
            this.dispose();
        });

        JPanel headerPanel = new JPanel();
        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblLogo)
                .addGap(10, 10, 10)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnLogout)
                .addGap(10, 10, 10))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogo)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addGap(2, 2, 2)
                        .addComponent(lblRole))
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(10, 10, 10))
        );

        lblSalesDays = new JLabel("Days with Sales Data: 0");
        lblWaiterPerf = new JLabel("Waiters in Performance Report: 0");
        lblChefPerf = new JLabel("Chefs in Performance Report: 0");

        JPanel navPanel = new JPanel();
        JButton btnNavDashboard = new JButton("Dashboard");
        JButton btnNavReports = new JButton("Reports");
        JButton btnNavPerformance = new JButton("Performance");
        JButton btnNavMenus = new JButton("Menus");
        JButton btnNavSettings = new JButton("Settings");

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnNavDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavPerformance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavMenus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavSettings)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNavDashboard)
                    .addComponent(btnNavReports)
                    .addComponent(btnNavPerformance)
                    .addComponent(btnNavMenus)
                    .addComponent(btnNavSettings))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        tableWaiters = new JTable(new DefaultTableModel(
            new Object[][]{},
            new String[]{"Waiter", "Orders", "Revenue", "Avg Order", "Peak Hour"}
        ));
        scrollWaiters = new JScrollPane(tableWaiters);

        tableChefs = new JTable(new DefaultTableModel(
            new Object[][]{},
            new String[]{"Chef", "Dishes", "Avg Prep (min)"}
        ));
        scrollChefs = new JScrollPane(tableChefs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalesDays, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(lblWaiterPerf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblChefPerf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollWaiters)
                    .addComponent(scrollChefs))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblSalesDays)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWaiterPerf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChefPerf)
                .addGap(10, 10, 10)
                .addComponent(scrollWaiters, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollChefs, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        SmartKitchenTheme.applyRoot(this);
        SmartKitchenTheme.styleCard(headerPanel);
        SmartKitchenTheme.styleCard(navPanel);
        SmartKitchenTheme.stylePrimaryLabel(lblWelcome);
        SmartKitchenTheme.styleSecondaryLabel(lblRole);
        SmartKitchenTheme.styleSecondaryLabel(lblSalesDays);
        SmartKitchenTheme.styleSecondaryLabel(lblWaiterPerf);
        SmartKitchenTheme.styleSecondaryLabel(lblChefPerf);
        SmartKitchenTheme.styleTable(tableWaiters);
        SmartKitchenTheme.styleTable(tableChefs);

        JButton[] navButtons = { btnNavDashboard, btnNavReports, btnNavPerformance, btnNavMenus, btnNavSettings };
        for (JButton b : navButtons) {
            b.setFocusPainted(false);
        }

        btnNavDashboard.addActionListener(e -> loadManagerMetrics());

        btnNavReports.addActionListener(e -> {
            javax.swing.JOptionPane.showMessageDialog(this, "TODO: Reports screen", "Not implemented",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });

        btnNavPerformance.addActionListener(e -> loadManagerMetrics());

        btnNavMenus.addActionListener(e -> {
            javax.swing.JOptionPane.showMessageDialog(this, "TODO: Menus screen", "Not implemented",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });

        btnNavSettings.addActionListener(e -> {
            javax.swing.JOptionPane.showMessageDialog(this, "TODO: Settings screen", "Not implemented",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });
    }// </editor-fold>//GEN-END:initComponents

    private void applyUserContext() {
        if (currentUser != null) {
            String name = currentUser.getUsername() != null && !currentUser.getUsername().isEmpty()
                    ? currentUser.getUsername()
                    : (currentUser.getEmail() != null ? currentUser.getEmail() : "Manager");
            lblWelcome.setText("Welcome, " + name);
            lblRole.setText("Role: " + currentUser.getRole());
            if (lblAvatar != null && name != null && !name.isEmpty()) {
                lblAvatar.setText(name.substring(0, 1).toUpperCase());
            }
        }
    }

    private void loadManagerMetrics() {
        if (currentUser == null || currentUser.getToken() == null) {
            return;
        }
        try {
            ReportService service = new ReportService();
            ReportService.SalesOverTimeOverview salesOverTime = service.getSalesOverTimeOverview(currentUser.getToken());
            ReportService.WaiterPerformanceOverview waiterOverview = service.getWaiterPerformanceOverview(currentUser.getToken());
            ReportService.ChefPerformanceOverview chefOverview = service.getChefPerformanceOverview(currentUser.getToken());

            lblSalesDays.setText("Days with Sales Data: " + salesOverTime.daysWithSales);
            lblWaiterPerf.setText("Waiters in Performance Report: " + waiterOverview.waiterCount);
            lblChefPerf.setText("Chefs in Performance Report: " + chefOverview.chefCount);

            java.util.List<ReportService.WaiterPerformanceRow> waiterRows =
                service.parseWaiterPerformance(service.getWaiterPerformanceRawJson(currentUser.getToken()));
            java.util.List<ReportService.ChefPerformanceRow> chefRows =
                service.parseChefPerformance(service.getChefPerformanceRawJson(currentUser.getToken()));

            DefaultTableModel waiterModel = (DefaultTableModel) tableWaiters.getModel();
            waiterModel.setRowCount(0);
            for (ReportService.WaiterPerformanceRow r : waiterRows) {
                waiterModel.addRow(new Object[]{
                    r.name,
                    r.totalOrdersServed,
                    String.format("%.2f", r.totalRevenue),
                    String.format("%.2f", r.averageOrderValue),
                    r.peakHour != null ? r.peakHour : "-"
                });
            }

            DefaultTableModel chefModel = (DefaultTableModel) tableChefs.getModel();
            chefModel.setRowCount(0);
            for (ReportService.ChefPerformanceRow r : chefRows) {
                chefModel.addRow(new Object[]{
                    r.name,
                    r.dishesPrepared,
                    r.averagePreparationTimeMinutes != null
                        ? String.format("%.2f", r.averagePreparationTimeMinutes)
                        : "-"
                });
            }
        } catch (Exception ex) {
            lblSalesDays.setText("Days with Sales Data: -");
            lblWaiterPerf.setText("Waiters in Performance Report: -");
            lblChefPerf.setText("Chefs in Performance Report: -");
            DefaultTableModel waiterModel = (DefaultTableModel) tableWaiters.getModel();
            waiterModel.setRowCount(0);
            DefaultTableModel chefModel = (DefaultTableModel) tableChefs.getModel();
            chefModel.setRowCount(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
