/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import model.User;
import service.OrderService;
import util.SmartKitchenTheme;

/**
 *
 * @author ntgr
 */
public class WaiterDashboardView extends javax.swing.JFrame {

    private User currentUser;
    private JLabel lblWelcome;
    private JLabel lblRole;
    private JLabel lblAvatar;
    private JLabel lblTablesAssigned;
    private JLabel lblOpenOrders;
    private JTable tableOpenOrders;
    private JScrollPane scrollOpenOrders;

    /**
     * Creates new form WaiterDashboardView
     */
    public WaiterDashboardView() {
        initComponents();
    }

    public WaiterDashboardView(User user) {
        this.currentUser = user;
        initComponents();
        applyUserContext();
        loadOrders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Kitchen - Waiter Dashboard");

        JLabel lblLogo = new JLabel();
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/images/logo.png"));
        java.awt.Image scaledLogo = logoIcon.getImage().getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
        lblLogo.setIcon(new ImageIcon(scaledLogo));

        lblWelcome = new JLabel("Welcome, Waiter");
        lblWelcome.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 16));

        lblRole = new JLabel("");

        lblAvatar = new JLabel("W", javax.swing.SwingConstants.CENTER);
        lblAvatar.setPreferredSize(new java.awt.Dimension(32, 32));
        lblAvatar.setOpaque(true);
        lblAvatar.setBackground(SmartKitchenTheme.ACCENT_GREEN);
        lblAvatar.setForeground(java.awt.Color.BLACK);

        JButton btnLogout = new JButton("Logout");
        btnLogout.addActionListener(e -> {
            new LoginView().setVisible(true);
            this.dispose();
        });

        JPanel headerPanel = new JPanel();
        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblLogo)
                .addGap(10, 10, 10)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnLogout)
                .addGap(10, 10, 10))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogo)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addGap(2, 2, 2)
                        .addComponent(lblRole))
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(10, 10, 10))
        );

        lblTablesAssigned = new JLabel("Tables Assigned: 0");
        lblOpenOrders = new JLabel("Open Orders: 0");

        JPanel navPanel = new JPanel();
        JButton btnNavDashboard = new JButton("Dashboard") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavMyTables = new JButton("My Tables") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavOpenOrders = new JButton("Open Orders") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavBills = new JButton("Bills") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };
        JButton btnNavSettings = new JButton("Settings") {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                SmartKitchenTheme.paintAccentGradient(g, this);
                super.paintComponent(g);
            }
        };

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnNavDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavMyTables)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavOpenOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavBills)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavSettings)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNavDashboard)
                    .addComponent(btnNavMyTables)
                    .addComponent(btnNavOpenOrders)
                    .addComponent(btnNavBills)
                    .addComponent(btnNavSettings))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        tableOpenOrders = new JTable(new DefaultTableModel(
            new Object[][]{},
            new String[]{"Order ID", "Table", "Status", "Total", "Order Date"}
        ));
        scrollOpenOrders = new JScrollPane(tableOpenOrders);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTablesAssigned, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(lblOpenOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollOpenOrders))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblTablesAssigned)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOpenOrders)
                .addGap(10, 10, 10)
                .addComponent(scrollOpenOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        SmartKitchenTheme.applyRoot(this);
        SmartKitchenTheme.styleCard(headerPanel);
        SmartKitchenTheme.styleCard(navPanel);
        SmartKitchenTheme.stylePrimaryLabel(lblWelcome);
        SmartKitchenTheme.styleSecondaryLabel(lblRole);
        SmartKitchenTheme.styleSecondaryLabel(lblTablesAssigned);
        SmartKitchenTheme.styleSecondaryLabel(lblOpenOrders);
        SmartKitchenTheme.styleTable(tableOpenOrders);

        JButton[] navButtons = { btnNavDashboard, btnNavMyTables, btnNavOpenOrders, btnNavBills, btnNavSettings };
        for (JButton b : navButtons) {
            SmartKitchenTheme.styleGradientButton(b);
        }

        btnNavDashboard.addActionListener(e -> loadOrders());

        btnNavMyTables.addActionListener(e -> {
            javax.swing.JOptionPane.showMessageDialog(this, "TODO: My Tables screen", "Not implemented",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });

        btnNavOpenOrders.addActionListener(e -> loadOrders());

        btnNavBills.addActionListener(e -> {
            javax.swing.JOptionPane.showMessageDialog(this, "TODO: Bills screen", "Not implemented",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });

        btnNavSettings.addActionListener(e -> {
            javax.swing.JOptionPane.showMessageDialog(this, "TODO: Settings screen", "Not implemented",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });
    }// </editor-fold>//GEN-END:initComponents

    private void applyUserContext() {
        if (currentUser != null) {
            String name = currentUser.getUsername() != null && !currentUser.getUsername().isEmpty()
                    ? currentUser.getUsername()
                    : (currentUser.getEmail() != null ? currentUser.getEmail() : "Waiter");
            lblWelcome.setText("Welcome, " + name);
            lblRole.setText("Role: " + currentUser.getRole());
            if (lblAvatar != null && name != null && !name.isEmpty()) {
                lblAvatar.setText(name.substring(0, 1).toUpperCase());
            }
        }
    }

    private void loadOrders() {
        if (currentUser == null || currentUser.getToken() == null) {
            return;
        }
        try {
            OrderService service = new OrderService();
            OrderService.WaiterOrdersResponse resp = service.getCurrentWaiterOrders(currentUser.getToken());

            lblTablesAssigned.setText("Tables Assigned: " + resp.stats.tablesAssigned);
            lblOpenOrders.setText("Open Orders: " + resp.stats.openOrdersCount);

            DefaultTableModel model = (DefaultTableModel) tableOpenOrders.getModel();
            model.setRowCount(0);
            for (OrderService.WaiterOpenOrderRow r : resp.openOrders) {
                model.addRow(new Object[]{
                    r.id,
                    r.tableNumber != null ? r.tableNumber : "-",
                    r.status,
                    String.format("%.2f", r.totalAmount),
                    r.orderDate != null ? r.orderDate : "-"
                });
            }
        } catch (Exception ex) {
            lblTablesAssigned.setText("Tables Assigned: -");
            lblOpenOrders.setText("Open Orders: -");
            DefaultTableModel model = (DefaultTableModel) tableOpenOrders.getModel();
            model.setRowCount(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaiterDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaiterDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaiterDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaiterDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WaiterDashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
